import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "primary-fixed": "#6bfe9c",
        "secondary-container": "#abd6ff",
        "on-primary": "#cdffd4",
        "error-dim": "#9f0519",
        tertiary: "#904800",
        "primary-container": "#6bfe9c",
        "primary-dim": "#005c2d",
        "inverse-on-surface": "#76a78d",
        "on-secondary": "#ebf4ff",
        "error-container": "#fb5151",
        "inverse-primary": "#6bfe9c",
        "tertiary-fixed": "#ff9742",
        "on-error": "#ffefee",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#aef1cc",
        "surface-container": "#b8f6d3",
        "on-error-container": "#570008",
        "on-tertiary-container": "#4f2500",
        "surface-variant": "#a4ecc5",
        "primary-fixed-dim": "#5bef90",
        "secondary-dim": "#005481",
        "secondary-fixed-dim": "#8ccaff",
        "on-secondary-container": "#004b74",
        "on-secondary-fixed": "#003757",
        "on-primary-fixed": "#004a23",
        "tertiary-dim": "#7e3e00",
        surface: "#dbffe8",
        "on-tertiary-fixed-variant": "#5d2c00",
        "on-tertiary": "#fff0e8",
        "tertiary-fixed-dim": "#f2882c",
        outline: "#518168",
        "on-surface-variant": "#35654d",
        error: "#b31b25",
        "tertiary-container": "#ff9742",
        "surface-dim": "#98e4bc",
        "surface-tint": "#006a35",
        "on-secondary-fixed-variant": "#005582",
        "on-background": "#003622",
        "surface-container-low": "#c4fedd",
        "outline-variant": "#86b89c",
        "on-tertiary-fixed": "#2b1100",
        "on-surface": "#003622",
        "inverse-surface": "#001209",
        "surface-container-highest": "#a4ecc5",
        "on-primary-container": "#005f2f",
        "secondary-fixed": "#abd6ff",
        "on-primary-fixed-variant": "#006a35",
        "surface-bright": "#dbffe8",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        DEFAULT: "1rem",
        xl: "2rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
